"""M3 — ``baron index``: regenerate the _handoff/README.md summary block and
verify ledger numbering.

The summary lives between ``BEGIN/END BARON INDEX`` HTML-comment markers so the
rest of README.md stays a human surface. Ledger verification is REPORT-ONLY:
duplicates are errors (exit 1), gaps and out-of-order headings are warnings —
baron never renumbers history (BaddieAnalyzer's F11–F13 out-of-order run and
its numbering gap are reproduced faithfully in that project's index, by design).
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from . import clock
from .handoff import iter_handoffs
from .ledger import KINDS, scan_ids

BEGIN_MARKER = "<!-- BEGIN BARON INDEX -->"
END_MARKER = "<!-- END BARON INDEX -->"

_DEFAULT_README = """# _handoff

Cross-persona async messages. Lifecycle: open -> done -> archived under
`archive/YYYY/` (never deleted). See COORDINATION.md for the protocol.

{block}
"""


@dataclass
class LedgerReport:
    kind: str
    duplicates: list[int]
    gaps: list[int]
    out_of_order: list[int]

    def to_dict(self) -> dict[str, object]:
        return {
            "kind": self.kind,
            "duplicates": self.duplicates,
            "gaps": self.gaps,
            "out_of_order": self.out_of_order,
        }


def build_block(collab: Path) -> str:
    active = iter_handoffs(collab)
    archived = list((collab / "_handoff").glob("archive/*/*.md"))
    open_h = [h for h in active if h.status == "open"]
    done_h = [h for h in active if h.status == "done"]
    other = len(active) - len(open_h) - len(done_h)

    lines = [
        BEGIN_MARKER,
        f"_Generated by `baron index` on {clock.today().isoformat()} — do not edit between these markers._",
        "",
        f"**Handoffs:** {len(open_h)} open · {len(done_h)} done · {len(archived)} archived"
        + (f" · {other} other" if other else ""),
    ]
    if open_h:
        lines += [
            "",
            "| Open handoff | For | From | Age (d) |",
            "|---|---|---|---|",
        ]
        for h in sorted(open_h, key=lambda h: h.created):
            age = h.age_days if h.age_days is not None else "?"
            lines.append(f"| [{h.path.name}]({h.path.name}) | {h.for_} | {h.from_} | {age} |")
    lines.append(END_MARKER)
    return "\n".join(lines)


def update_readme(collab: Path) -> Path:
    readme = collab / "_handoff" / "README.md"
    block = build_block(collab)
    if readme.is_file():
        text = readme.read_text(encoding="utf-8")
        if BEGIN_MARKER in text and END_MARKER in text:
            head, _, rest = text.partition(BEGIN_MARKER)
            _, _, tail = rest.partition(END_MARKER)
            text = head + block + tail
        else:
            text = text.rstrip("\n") + "\n\n" + block + "\n"
    else:
        readme.parent.mkdir(parents=True, exist_ok=True)
        text = _DEFAULT_README.format(block=block)
    readme.write_text(text, encoding="utf-8")
    return readme


def check_ledger(collab: Path, kind_name: str) -> LedgerReport | None:
    kind = KINDS[kind_name]
    index_path = collab / kind.index
    if not index_path.is_file():
        return None
    ids = scan_ids(index_path.read_text(encoding="utf-8"), kind.prefix)
    seen: set[int] = set()
    duplicate_set: set[int] = set()
    for i in ids:
        if i in seen:
            duplicate_set.add(i)
        seen.add(i)
    duplicates = sorted(duplicate_set)
    unique_sorted = sorted(seen)
    gaps: list[int] = []
    for a, b in zip(unique_sorted, unique_sorted[1:]):
        gaps.extend(range(a + 1, b))
    out_of_order = [b for a, b in zip(ids, ids[1:]) if b < a and b not in duplicates]
    return LedgerReport(kind_name, duplicates, gaps, out_of_order)
